# Services optimized for APISIX
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi-backend
spec:
  selector:
    app: fastapi-backend
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react-frontend
spec:
  selector:
    app: react-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP